source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftEvery', :exclusive => true do
  pod "SwiftEvery", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SwiftEvery", :path => "../"

  
end
